name: bingo
description: "A high-performance, synchronous state storage engine for Flutter with built-in caching and type-safe object registration."
version: 1.0.0
homepage: https://github.com/RadoDayef/bingo
repository: https://github.com/RadoDayef/bingo

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.8.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true